name: OfflineEncryptor
version: $version
main: io.github.lumine1909.offlineencryptor.paper.OfflineEncryptor
api-version: 1.20
folia-supported: true
softdepend:
  - ViaVersion
  - LimitedOfflineMode
authors:
  - Lumine1909